# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald
  font: serif

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Dr. Halley Pontes is an internationally awarded psychologist specializing in addictive behaviors such as gaming disorder and other addictions'
    twitter: 'DrHalleyPontes'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: 'JGmMkHpXSwdliZ3YUNpsonNJRMHBLOSA'
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Dr. Halley Pontes" #modify for text on the left side

# Site footer
footer:
  copyright:
    notice: '© {year} Dr. Halley Pontes. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '15:04'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
